### ISSUE TITLE
Error: "TypeError: 'dict_keys' object does not support indexing" on gen_data.create_phone()

### ISSUE THREAD

**Issue by bmcguirk** [chris1610/barnum-proj#6]
```
>>> from barnum import gencc, gen_data
>>> gen_data.create_name()
('Benita', 'Yost')
>>> gen_data.create_name()
('Marian', 'Rector')
>>> gen_data.create_name()
('Carly', 'Knott')
>>> gen_data.create_name()
('Elaine', 'Knotts')
>>> gen_data.create_name()
('Abraham', 'Kersey')
>>> gen_data.create_name()
('Burt', 'Sheppard')
>>> gen_data.create_phone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\barnum\gen_data.py", line 77, in create_phone
    zip_code = random.choice(all_zips.keys())
  File "C:\Anaconda3\lib\random.py", line 256, in choice
    return seq[i]
TypeError: 'dict_keys' object does not support indexing
```

Using Anaconda to manage packages. Here's the env info:
```
Current conda install:

             platform : win-64
        conda version : 3.19.1
  conda-build version : 1.18.2
       python version : 3.4.4.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\brian.mcguirk\.condarc
    is foreign system : False
```

**Comment by chris1610** [comment]
Try the latest version via a pip upgrade. I think I resolved it so that it works in python 2 and 3.
